
export const data=[
    {id:0,
     productname:"brush",
     productvalue:"100",
     cartstatus:"false",
     starstatus:"true",
     salestatus:"true",
     startcount:2,
     priceslashed:"500"
    },

    {id:1,
        productname:"tooth paste",
        productvalue:"500",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"false",
        startcount:3,
        priceslashed:"50"
       },

       {id:2,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"100"
       },
       {id:3,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"20"
       }, 
       {id:4,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"100"
       },
       {id:5,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"60"
       },
       {id:6,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"70"
       },
       {id:7,
        productname:"facewash",
        productvalue:"200",
        cartstatus:"false",
        starstatus:"true",
        salestatus:"true",
        startcount:3,
        priceslashed:"80"
       }
    ]


